[General]
showlogo=hidden
showClock=true
logo=default-logo.svg
type=web
color=#1d99f3
fontSize=10
background=/usr/share/wallpapers/Next/contents/images/5120x2880.png
webBackground=html/thinkpad-ambient.html
webFps=30
webScale=60
needsFullUserModel=false
